server {
    listen 80;
    server_name _;

    location ~ ^/api/v1/admin {
        proxy_pass http://localhost:9381;
        include /etc/nginx/proxy.conf;
    }

    location ~ ^/(v1|api) {
        proxy_pass http://localhost:9380;
        include /etc/nginx/proxy.conf;
    }

    location / {
        root /ragflow/web/dist;
        try_files $uri $uri/ /index.html;
        gzip on;
        gzip_comp_level 9;
        gzip_types text/plain text/css text/javascript application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss image/jpeg image/gif image/png;
    }

    location ~* \.(css|js|jpg|jpeg|gif|png|ico|svg|woff|woff2|ttf|eot)$ {
        root /ragflow/web/dist;
        expires 10y;
        access_log off;
        add_header Cache-Control "public, immutable";
    }
}
